workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: 3.24.5
      xcode: latest 
      cocoapods: default
    triggering:
      events:
        - push
    scripts:
      - name: Instalar Dependencias
        script: flutter pub get

      - name: Configurar Firma de Apple
        script: |
          keychain initialize
          xcode-project use-profiles

      - name: Compilar IPA para App Store
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist --code-sign-style=manual

    artifacts:
      - build/ios/ipa/*.ipa
